name: Publish Dotnet Package

on:
  workflow_call:

jobs:
  build_packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v6.0.0
      with:
        dotnet-version: 8.0.x
    - name: Define VERSION
      if: github.event_name == 'release'
      run: |
        echo "Version: " ${{ github.ref_name }}
        echo "VERSION=$(echo "${{ github.ref_name }}" | cut -c 2-)" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./Coverage/ --no-build --verbosity normal
    - name: Report coverage
      uses: danielpalme/ReportGenerator-GitHub-Action@5.5.11
      with:
        reports: ./**/Coverage/coverage.cobertura.xml
        reportTypes: HtmlInline;Cobertura;MarkdownSummaryGithub
        targetdir: ./Coverage/
        customSettings: 'minimumCoverageThresholds:lineCoverage=90'
    - name: Upload test coverage artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: test coverage
        path: ./Coverage/
    - name: Publish test coverage in build summary
      run: cat ./Coverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
      shell: bash
    - name: Pack
      if: github.event_name == 'release'
      run: dotnet pack /p:Version=$VERSION --configuration Release --output ./nupkg
    - name: Publish
      if: github.event_name == 'release'
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
