name: Publish Dotnet Package

on:
  workflow_call:

jobs:
  build_packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v6.0.0
      with:
        dotnet-version: 8.0.x
    - name: Define VERSION
      if: github.event_name == 'release'
      run: |
        echo "Version: " $ref_name
        echo "VERSION=$(echo "$ref_name" | cut -c 2-)" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:MergeWith=../../TestResults/totalcoverage.cobertura.xml /p:CoverletOutputFormat=cobertura --no-build --verbosity normal
    - name: Report Coverage
      uses: danielpalme/ReportGenerator-GitHub-Action@5.5.11
      with:
        reports: ./TestResults/totalcoverage.cobertura.xml
    - name: Pack
      if: github.event_name == 'release'
      run: dotnet pack /p:Version=$VERSION --configuration Release --output ./nupkg
    - name: Publish
      if: github.event_name == 'release'
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate
